.\" Manpage for screenfetch-c
.\" Contact woodruffw on GitHub or at william @ tuffbizz.com to report any bugs or errors
.TH screenfetch-c 1 "04 August 2013" "1.3r" "User Commands" 
.SH NAME
.BR screenfetch-c " - Display computer information and an ASCII logo"
.SH SYNOPSIS
.B screenfetch-c
.RI [ OPTIONS ]
.SH DESCRIPTION
.B screenfetch-c
is a C rewrite of the original screenFetch, which was written in bash by Brett Bohnenkamper. 
Like the original, it displays both an ASCII logo determined by the computer's OS and a variety of statistics, including kernel type, ram, uptime, and so forth.
.SH COMPATIBILITY
Supported OSes:
Microsoft Windows, Mac OS X, FreeBSD, OpenBSD, NetBSD, DragonFlyBSD, Solaris and its derivatives, 
and most Linux-kernel based distributions.
.PP
.I Note:
If you are using manual mode to provide
.B screenfetch-c
with system information, you will need to enter the distribution name EXACTLY as written below:
Arch Linux, ParabolaGNU/Linux-libre, Chakra, Manjaro, Frugalware, Ubuntu, LinuxMint, SolusOS, Debian, LMDE, CrunchBang, Peppermint, LinuxDeepin, Trisquel, elementary OS, Backtrack Linux, Slackware, Gentoo, Sabayon, Funtoo, Fuduntu, Fedora, OpenSUSE, Red Hat Linux, Mandriva, Mandrake, Mageia, Viperr, Andoid, Linux, Solaris, Angstrom.
.PP
Supported shells:
GNU bash, csh, zsh, ksh, fish, dash, ash.
.SH OPTIONS
.PP
.BR \-v ,
.B\-\-verbose
.PP
Enable verbose mode, which prints out detection information.
.PP
.BR \-s ,
.B \-\-screenshot
.PP
Take a screenshot after completing the output.
On non\-Windows systems, this will save a file titled
.RI ' screenfetch_screenshot.png '
in
.BR $HOME .
On Windows, this will save the screenshot in the system clipboard.
.PP
.BR \-n ,
.B \-\-no-logo
.PP
Strip output of ASCII logo - print information only.
.PP
.BR \-D ,
.BI \-\-distro " DISTRO"
.PP
Set the distro outputted by
.BR screenfetch-c .
.PP
.BR \-E ,
.B \-\-suppress-errors
.PP
Suppress (most) error messages as they arise.
.PP
.BR \-p ,
.B \-\-portrait
.PP
Print output in portrait mode.
.PP
.BR \-V ,
.B \-\-version
.PP
Display the version of
.B screenfetch-c
currently being used.
.PP
.BR \-h ,
.B \-\-help
.PP
Displays help and compatibility information.
.PP
.BR \-L ,
.BI \-\-logo-only " DISTRO"
.PP
Output only the ASCII logo associated with that distro. Follows the general naming conventions of the
.B \-D
flag, but with "OS X", "Windows", and "Solaris" as possibilities as well.
.SH CONFIGURATION
When
.B screenfetch-c
is invoked with the
.B \-m
flag for the first time, it enters manual mode.
Manual mode prompts the user to enter specific information about the computer, storing that information in
.RI ~/ .screenfetchc
for the next invocation with the
.B \-m
flag.
.PP
By default, you must enter all fields asked for in manual mode. However, if you want
.B screenfetch-c
to skip a particular field while reading from the file, enter an asterisk ("*") for that section.
This will force
.B screenfetch-c
to attempt to detect that section, which may come in handy if you want to use manual mode for some sections but not for others.
.PP
To remove your existing manual configuration, simply delete the
.I .screenfetchc
file located in your
.BR $HOME . 
.PP
Note:
.IR .screenfetchc 's
format isn't exactly human-friendly, so editing it manually is
.B NOT
recommended.
.SH ENVIRONMENT
.B screenfetch-c
uses the following environment variables:
.PP
.BR USER " - Used on BSD to determine the current user."
.PP
.BR HOME " - Used to determine the user's home directory."
.PP
.BR SHELL " - Used to determine the active shell."
.PP
Each of these variables must be defined properly in order for
.B screenfetch-c
to function as intended.
.SH RELEASE HISTORY
.IR 0.1 " - ALPHA - INCOMPLETE, UNCOMPILED"
.PP
.IR 0.5 " - ALPHA - INCOMPLETE, TEST COMPILED"
.PP
.IR 1.0 " - BETA - LACKING MINOR PARTS, STABLE, WORKING ON MOST SYSTEMS"
.PP
.IR 1.1 " - BETA - NEARLY COMPLETE, MINOR BUGS AND GPU DETECTION NOT FINISHED"
.PP
.IR 1.2 " - RELEASE - WORKS ON THE MAJORITY OF SYSTEMS"
.PP
.IR 1.3 " - RELEASE - SIGNIFICANT REFACTORING AND PERFORMANCE IMPROVEMENTS"
.SH BUGS AND ERRATIC BEHAVIOR
Shell version detection relies of very specific naming schemes and may appear incorrectly if any shell changes its versioning scheme.
.PP
DragonFly BSD systems with more than 4GiB of RAM may have their RAM stats displayed incorrectly, as 32-bit integers are used in sysctl.
.PP
Manual mode on Windows seems the result in a variety of weird bugs concerning uptime, packages, disk stats, and memory stats. For the time being, I recommend NOT using it on Windows.
.PP
Memory detection on Linux systems includes swap/buffer RAM in used RAM, not free RAM. While this is not a bug per se, it may contradict figures from other utilities (which factor out swap/buffer RAM).
.PP
Found a bug or issue? Please tell me about it:
.I http://github.com/woodruffw/screenfetch-c
.SH DIAGNOSTICS
.B screenfetch-c
has two built-in output modes: verbose (disabled by default) and error (enabled by default).
If a serious or fatal error occurs, the user will be notified via error (stderr).
Otherwise, the user may choose to enable the verbose mode, which display real-time detection.
.SH EXIT STATUS
.B screenfetch-c
returns
.B EXIT_SUCCESS
in all circumstances except for malformed argument strings.
For example,
.B screenfetch-c
will return
.B EXIT_FAILURE
if flagged with
.B \-D
but not given an additional argument.
.SH AUTHOR
.B screenfetch-c
was written and is maintained by William Woodruff
.RI ( "william @ tuffbizz.com" )
.PP
The original screenFetch was written by Brett Bohnenkamper
.RI ( "kittykatt @ archlinux.us" )
.PP
For a list of contributors to
.BR screenfetch-c ,
please refer to the CONTRIBUTORS file.
.SH SEE ALSO
.BR screenFetch (1)
